# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Build mac app"
  lane :ci_build do |options|
    version = options[:version]
    UI.user_error!("No version found") unless version

    build_number = options[:build]
    UI.user_error!("No build number found") unless build_number

    bump_version(version_number: version)
    increment_build_number(build_number: build_number)

    xcode_select("/Applications/Xcode_26.3.app")
    gym()
  end

  desc "Create a keychain and import the certificate for code signing"
  lane :cert_keychain do |options|
    cert_path = options[:path] 

    create_keychain(
      name: "CertKeychain",
      default_keychain: true,
      unlock: true,
      timeout: 0,
      password: ENV["KEYCHAIN_PASSWORD"] || "default"
    )
    import_certificate(
      certificate_path: cert_path,
      certificate_password: ENV["CERT_PASSWORD"] || "default",
      keychain_name: "CertKeychain",
      keychain_password: ENV["KEYCHAIN_PASSWORD"] || "default"
    )
  end

  desc "Delete the keychain created for code signing"
  lane :delete_cert_keychain do
    delete_keychain(name: "CertKeychain")
  end

  desc "Bump version"
  lane :bump_version do |options|
    version_number = options[:version_number]
    UI.user_error!("No version found") unless version_number
    path = "../Blink.xcodeproj/project.pbxproj"
    if `sed --version 2>&1`.include?("GNU")
      sh(%Q(sed -i -e 's/MARKETING_VERSION \\= [^\\;]*\\;/MARKETING_VERSION = #{version_number};/' #{path}))
    else
      sh(%Q(sed -i '' -e 's/MARKETING_VERSION \\= [^\\;]*\\;/MARKETING_VERSION = #{version_number};/' #{path}))
    end
  end
end
